import { mkdir, rm, writeFile } from 'fs/promises';
import { ModuleGenerator } from './modulegen';
import { TypeGenerator } from './typegen';
import { type CategoryConfig, type UserConfig } from './types';

const noteComment = '// NOTE: This file is auto-generated by mdorganizer.';

export class MdOrganizer {
  private typeGenerator: TypeGenerator;
  private moduleGenerator: ModuleGenerator;
  private documentConfigs: CategoryConfig[];

  constructor(config: UserConfig) {
    this.typeGenerator = new TypeGenerator(config);
    this.moduleGenerator = new ModuleGenerator(config);
    this.documentConfigs = config.documents;
  }

  async generateGeneratedFolder(): Promise<void> {
    await rm('.mdorganizer/generated', { recursive: true, force: true });
    await mkdir('.mdorganizer/generated', { recursive: true });
    for (const config of this.documentConfigs) {
      await mkdir(`.mdorganizer/generated/${config.documentCategory}`, {
        recursive: true,
      });
    }
    return;
  }

  /**
   * @memberof MdOrganizer
   * @description Generates all category/types.d.ts files.
   * @returns {Promise<void>}
   */
  async generateAllCategoryTypeFiles(): Promise<void> {
    const types = this.typeGenerator.generateAll();
    for (const type of types) {
      await writeFile(
        `.mdorganizer/generated/${type.documentCategory}/types.d.ts`,
        `${noteComment}\n\n${type.generatedTypeString}`,
        { flag: 'w+' },
      );
    }
    return;
  }

  async generateAllModules(): Promise<void> {
    const categoryModules = await this.moduleGenerator.generateAll();
    for (const categoryModule of categoryModules) {
      for (const doc of categoryModule.documentModules) {
        await writeFile(
          `.mdorganizer/generated/${categoryModule.documentCategory}/${doc.documentId}.ts`,
          doc.generatedModuleString,
        );
      }

      const categoryCapitalized =
        categoryModule.documentCategory.charAt(0).toUpperCase() + categoryModule.documentCategory.slice(1);

      // category/index.ts
      let imports = `import type { ${categoryCapitalized}Document } from './types.d.ts';\n`;
      let exports = `export const all${categoryCapitalized}Documents: ${categoryCapitalized}Document[] = [\n`;
      for (const documentModule of categoryModule.documentModules) {
        imports += `import ${documentModule.documentId} from './${documentModule.documentId}';\n`;
        exports += `  ${documentModule.documentId},\n`;
      }
      exports += '];\n';
      await writeFile(
        `.mdorganizer/generated/${categoryModule.documentCategory}/index.ts`,
        `${noteComment}\n\n${imports}\n${exports}`,
      );
    }
    return;
  }

  async generateIndexFiles(): Promise<void> {
    await writeFile(
      '.mdorganizer/generated/types.d.ts',
      `${noteComment}\n\n${this.documentConfigs
        .map((documentConfig) => {
          return `export type * from './${documentConfig.documentCategory}/types.d.ts';\n`;
        })
        .join('\n')}`,
      {
        flag: 'w+',
      },
    );

    await writeFile(
      '.mdorganizer/generated/index.d.ts',
      `${noteComment}\n\nexport type * from './types';\n${this.documentConfigs
        .map((documentConfig) => {
          return `export * from './${documentConfig.documentCategory}';`;
        })
        .join('\n')}\n`,
      {
        flag: 'w+',
      },
    );

    return;
  }
}
